name: lint-test-build

on: [pull_request, push]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Format check
        run: yarn format:check
      - name: Unit Testing
        run: yarn test
        env:
          CI: true
      - name: Production build
        run: yarn build
